USE UxForms
GO

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				 WHERE TABLE_SCHEMA = 'app' 
                 AND  TABLE_NAME = 'Form'))
BEGIN
	CREATE TABLE app.[Form] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[Name] NVARCHAR(255) NULL,
		[Created] [DATETIME] NULL CONSTRAINT [DF_Form_Created] DEFAULT (GETUTCDATE()),
		[Modified] [DATETIME],
	    CONSTRAINT [PK_Form] PRIMARY KEY CLUSTERED ([Id] ASC)
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'User'))
BEGIN
	CREATE TABLE app.[User] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[Name] NVARCHAR(255) NULL,
		[Created] [DATETIME] NULL CONSTRAINT [DF_User_Created] DEFAULT (GETUTCDATE()),
	    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'Field'))
BEGIN
	CREATE TABLE app.[Field] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[FormId] INT NOT NULL,
		[Name] NVARCHAR(255),
		[FieldType] INT,
		[Created] [DATETIME] NULL CONSTRAINT [DF_Field_Created] DEFAULT (GETUTCDATE()),
	    CONSTRAINT [PK_Field] PRIMARY KEY CLUSTERED ([Id] ASC),
	    CONSTRAINT [FK_Field_Form] FOREIGN KEY ([FormId]) REFERENCES app.[Form] ([Id]),
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'FieldType'))
BEGIN
	CREATE TABLE app.[FieldType] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[Name] NVARCHAR(255),
		[Created] [DATETIME] NULL CONSTRAINT [DF_FieldType_Created] DEFAULT (GETUTCDATE()),
		CONSTRAINT [PK_FieldType] PRIMARY KEY CLUSTERED ([Id] ASC)
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'Answer'))
BEGIN
	CREATE TABLE app.[Answer] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[FieldId] INT NOT NULL,
		[Name] NVARCHAR(255),
		[Created] [DATETIME] NULL CONSTRAINT [DF_Answer_Created] DEFAULT (GETUTCDATE()),
		CONSTRAINT [PK_Answer] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [FK_Answer_Field] FOREIGN KEY ([FieldId]) REFERENCES app.[Field] ([Id])
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'UserAnswer'))
BEGIN
	CREATE TABLE app.[UserAnswer] (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[UserId] INT NOT NULL,
		[AnswerId] INT NOT NULL,
		[Created] [DATETIME] NULL CONSTRAINT [DF_UserAnswer_Created] DEFAULT (GETUTCDATE()),
		CONSTRAINT [PK_UserAnswer] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [FK_UserAnswer_User] FOREIGN KEY ([UserId]) REFERENCES app.[User] ([Id]),
		CONSTRAINT [FK_UserAnswer_Answer] FOREIGN KEY ([AnswerId]) REFERENCES app.[Answer] ([Id])
	);
END

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'UserFormScore'))
BEGIN
	CREATE TABLE app.UserFormScore (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[FormId] INT NOT NULL,
		[UserId] INT NOT NULL,
		[Score] INT NOT NULL,
		[Created] [DATETIME] NULL CONSTRAINT [DF_UserFormScore_Created] DEFAULT (GETUTCDATE()),
		CONSTRAINT [PK_UserFormScore] PRIMARY KEY CLUSTERED ([Id] ASC),
		CONSTRAINT [FK_UserFormScore_Form] FOREIGN KEY ([FormId]) REFERENCES app.[Form] ([Id]),
		CONSTRAINT [FK_UserFormScore_User] FOREIGN KEY ([UserId]) REFERENCES app.[User] ([Id])
	);
END
